en/h3-https.md
"Preciously" changed to "previously"
I haven't used source control since Cogito, so apologies if this is too small a change or if I'm not submitting this request correctly
=> Fixed typo

en/why-h2.md
Also, rework the sentence fragment.
=> Idiomatic American English.

zh/README.md
added translator's name and contact
=> added translator's name and contact

en/feature-udp.md
It's not inherent in the protocol itself.
=> Clarify "user-space"

en/feature-inorder.md, en/proc-ietf.md, en/quic-0rtt.md, en/quic-connections.md, en/quic-tls.md, en/quic-userspace.md, en/quic.md, en/why-tcpudp.md
Mostly minor simplifications of the language. A few clarifications based on my first read.
Thanks for taking a look!
=> Propose various wording tweaks

en/proc.md
That sentence wasn't right, "that is" means nothing here.
=> Remove "that is" in proc.md

en/quic-connections.md
The end of this sentence is crazy, it needs to be reformulated 😕
=> Remove "when going forward" in quic-connections.md

HOWTO-TRANSLATE.md
I made a separated PR to split the traduction from the other things
=> Add Nathanael Demacon to main translators list

en/h3-push.md
=> "high level a certainty" to "high level of certainty" in h3-push.md

en/specs.md
Apply requests #54, #55, #56, #57 and #58.
=> Update links in spec.md

en/why-ossification.md
This needs verification but the actual sentence is barely understandable (or maybe it's me 😢)
=> Correct sentence in why-ossification.md

en/specs.md
quic draft 18 was released last week :D
=> update draft url

en/feature-nonhttp.md, en/why-ossification.md, en/why-secure.md, en/why-tcphol.md
Hi, I've made a few changes to some of the (English) grammar. Please let me know if you want any of these changed in any way.
=> Grammar improvements

en/why-tcphol.md
Small nitpick: changed "less good" to "less well".
=> [en] small grammatical improvement

fr/criticism.md
The paragraph is already translated just above :wink:
=> Fix duplicated paragraph

fr/SUMMARY.md, fr/feature-http.md
Follow [this update](https://github.com/bagder/http3-explained/commit/603e1d25fa00d4a1785546be227d41d324129a86) in the French translation.
=> fr: change the title of feature-http.md to "HTTP/3 sur QUIC"

ko/quic-streams.md
Hello.
Thank you for making a good book.
I fix typos of Korean translation
Thank you for reading.
=> (ko) fixed typo

ko/feature-trans-app.md
Hello
I've made some changes to make the text look more natural.
Please let me know if there are any additional repository management guidelines I should follow.
Thank you.
=> [Protocol features] [ko] [tiny translation improvements]

ko/specs.md
Updated drafts URLs for Korean
ref: https://github.com/bagder/http3-explained/pull/100
=> [ko] Updated drafts URLs

en/proc-status.md
Added notes (and links) about NGINX and Mozilla IETF-QUIC+HTTP/3 implementation plans.
=> Added notes on NGINX and Mozilla implementation plans

en/specs.md, fr/specs.md, it/specs.md, ja/specs.md, ko/specs.md, ro/specs.md, zh/specs.md
HTTP/3 and QPACK new versions are now out!
=> update draft urls

ja/proc-status.md
Translated #122 into Japanese.
=> [ja] add implementation plans

fr/README.md
=> [fr] Fix doc

ko/README.md
=> [ko] Fix doc

en/README.md
=> [en] Fix doc

zh/README.md
=> [zh] Fix doc

it/README.md
=> [it] Fix doc

ro/README.md
=> [ro] Fix doc

en/criticism.md, en/h3-prio.md, en/proc-h2.md, en/proc-ietf.md, en/proc-status.md, en/quic-streams.md, en/specs.md
Probably a bit of a never ending task to keep this up to date but some parts of the book are looking a little dated now so thought I'd submit this PR to bring it up to speed with the latest that I'm aware of.
Let me know your thoughts.
=> Updates to bring this up to date with latest changes in HTTP/3

ja/proc-status.md
References
- https://github.com/bagder/http3-explained/pull/122#issuecomment-529846486
- https://github.com/bagder/http3-explained/commit/598f92a725270d6e0fd213a2dbad87df80e1297d
=> [ja] follow update (curl h3 support)

fa/specs.md
Refine, rephrase, and fix syntactic errors.
=> [fa] Update specs.md

SUMMARY.md, it/README.md, it/h3-h2.md, it/h3-prio.md, it/h3-push.md, it/h3-streams.md, it/h3.md, it/quic-spinbit.md, it/quic-v2.md, it/why-quic.md, it/why-tcphol.md, it/why-tcpudp.md
* replace incorrect grave accents with acute accents.
* replace "E'" with "È".
* replace "alchè" (???) with "e dopo" ("and then").
=> it: fix some accents

en/proc-ietf.md
Updated proc-ietf.md to add QUIC protocol published date.
It was not known when this file was last updated.
Added QUIC Protocol published data and RFC Link.
=> Updated proc-ietf.md to add QUIC published date

en/h3-h2.md, en/h3-prio.md, en/quic-streams.md
The work has been completed now, so we can drop speculation. 
I went for brevity in this text, since correctness is more important than fullness. Followup work can expand details if people would find that useful.
=> Tidy up text related to prioritization now that we have RFC 9218

en/h3.md
=> Fix language typo in h3.md

fr/criticism.md, fr/feature-trans-app.md, fr/why-secure.md
Hi!
Thank you for making and providing this great doc on HTTP/3.
While reading it, I noticed some typos and formulations which could be improved.
So here is a short PR.
=> [fr] Fix some formulations and typos in the french translation
